-- Seed email templates and settings
-- Email Templates
INSERT INTO "EmailTemplate" (key, name, category, subject, body, variables, enabled, required, created_at, updated_at) VALUES
('submission_confirmed', 'Submission Confirmed', 'applications', '🎉 IPT Placement Confirmed — {{studentName}}', '<div style="font-family: Arial, sans-serif; max-width: 640px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #2563eb, #1d4ed8); padding: 32px; border-radius: 16px 16px 0 0; text-align: center;"><h1 style="color: white; margin: 0; font-size: 24px;">🎉 IPT Placement Confirmed!</h1><p style="color: #bfdbfe; margin: 8px 0 0; font-size: 14px;">Industrial Practical Training 2025/2026</p></div><div style="background: #f8fafc; padding: 32px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 16px 16px;"><p style="font-size: 16px; color: #1e293b;">Dear <strong>{{studentName}}</strong> ({{studentId}}),</p><p style="color: #475569; line-height: 1.6;">Congratulations! Your IPT cluster placement has been confirmed.</p><div style="background: white; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; margin: 24px 0;"><div style="padding: 20px; border-bottom: 1px solid #e2e8f0;"><h3 style="margin: 0 0 8px; color: #2563eb;">Phase 1 — {{phase1Cluster}}</h3><p style="margin: 0; color: #64748b; font-size: 13px;">{{phase1Dates}}</p><p style="margin: 4px 0; color: #64748b; font-size: 13px;">Supervisors: {{phase1Staff}}</p></div><div style="padding: 20px;"><h3 style="margin: 0 0 8px; color: #059669;">Phase 2 — {{phase2Cluster}}</h3><p style="margin: 0; color: #64748b; font-size: 13px;">{{phase2Dates}}</p><p style="margin: 4px 0; color: #64748b; font-size: 13px;">Supervisors: {{phase2Staff}}</p></div></div><p style="color: #64748b; font-size: 14px;">Please report to your assigned cluster on the start date.</p></div></div>', '["studentName","studentId","phase1Cluster","phase1Dates","phase1Staff","phase2Cluster","phase2Dates","phase2Staff"]', true, true, NOW(), NOW()),
('allocation_confirmed', 'Allocation Confirmed', 'applications', 'IPT Allocation — {{clusterName}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: #2563eb; padding: 24px; border-radius: 12px 12px 0 0;"><h1 style="color: white; margin: 0; font-size: 20px;">IPT Allocation Confirmed</h1></div><div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;"><p>Dear <strong>{{studentName}}</strong> ({{studentId}}),</p><p>Your IPT cluster allocation has been confirmed:</p><div style="background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0;"><p style="margin: 0; font-size: 18px; font-weight: bold; color: #2563eb;">{{clusterName}}</p><p style="margin: 8px 0 0; color: #64748b;">Location: {{clusterLocation}}</p></div><p style="color: #64748b; font-size: 14px;">Please report to the cluster location on the start date.</p></div></div>', '["studentName","studentId","clusterName","clusterLocation"]', true, true, NOW(), NOW()),
('transfer_approved', 'Transfer Approved', 'transfers', '✅ Transfer Approved — {{clusterName}}', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: #059669; padding: 24px; border-radius: 12px 12px 0 0;"><h1 style="color: white; margin: 0; font-size: 20px;">✅ Transfer Approved</h1></div><div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;"><p>Dear <strong>{{studentName}}</strong> ({{studentId}}),</p><p>Your cluster transfer request has been <strong style="color: #059669;">approved</strong>.</p><div style="background: white; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0;"><p style="margin: 0; font-size: 18px; font-weight: bold; color: #059669;">{{clusterName}}</p><p style="margin: 8px 0 0; color: #64748b;">Location: {{clusterLocation}}</p></div><p style="color: #64748b; font-size: 14px;">Please report to your new cluster immediately.</p></div></div>', '["studentName","studentId","clusterName","clusterLocation"]', true, true, NOW(), NOW()),
('transfer_rejected', 'Transfer Rejected', 'transfers', '❌ Transfer Request Update', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: #dc2626; padding: 24px; border-radius: 12px 12px 0 0;"><h1 style="color: white; margin: 0; font-size: 20px;">❌ Transfer Not Approved</h1></div><div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;"><p>Dear <strong>{{studentName}}</strong> ({{studentId}}),</p><p>Your cluster transfer request has been <strong style="color: #dc2626;">not approved</strong>.</p><div style="background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 16px; margin: 16px 0;"><p style="margin: 0; font-size: 14px; color: #991b1b;"><strong>Reason:</strong> {{reason}}</p></div><p style="color: #64748b; font-size: 14px;">You will remain in your current cluster: <strong>{{clusterName}}</strong>.</p></div></div>', '["studentName","studentId","clusterName","reason"]', true, true, NOW(), NOW()),
('report_reminder', 'Report Reminder', 'applications', 'IPT Report Submission Reminder', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: #f59e0b; padding: 24px; border-radius: 12px 12px 0 0;"><h1 style="color: white; margin: 0; font-size: 20px;">📋 Report Reminder</h1></div><div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;"><p>Dear <strong>{{studentName}}</strong>,</p><p>This is a reminder to submit your IPT report before the deadline.</p><p>Please log in to the IPT portal to upload your report.</p></div></div>', '["studentName"]', true, false, NOW(), NOW()),
('test_email', 'Test Email', 'system', 'IPT Test Email', '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: #6366f1; padding: 24px; border-radius: 12px 12px 0 0;"><h1 style="color: white; margin: 0; font-size: 20px;">🧪 Test Email</h1></div><div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;"><p>This is a test email from the IPT Application System.</p><p>If you received this, your email configuration is working correctly.</p><p style="color: #94a3b8; font-size: 12px;">Sent at: {{timestamp}}</p></div></div>', '["timestamp"]', true, false, NOW(), NOW())
ON CONFLICT (key) DO NOTHING;

-- SMTP Settings
INSERT INTO "Setting" (key, value, type, updated_at) VALUES
('smtp_host', '', 'string', NOW()),
('smtp_port', '587', 'string', NOW()),
('smtp_secure', 'false', 'boolean', NOW()),
('smtp_user', '', 'string', NOW()),
('smtp_pass', '', 'password', NOW()),
('smtp_from', 'noreply@ipt.herpydevs.com', 'string', NOW()),
('smtp_sender_name', 'IPT System', 'string', NOW())
ON CONFLICT (key) DO NOTHING;
